tunnel: YOUR_TUNNEL_ID
credentials-file: /opt/cloudflare/credentials.json

ingress:
  - hostname: ambu.cfvision.in
    service: http://localhost:9322
  - hostname: driver.cfvision.in
    service: http://localhost:5175
  - hostname: ambuadmin.cfvision.in
    service: http://localhost:5176
  - service: http_status:404
